In [122]:
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


***Q1. Create NumPy arrays from the ages and salaries data generated above. Print both arrays and display their dtype, ndim, shape, and size.***

In [244]:
import numpy as np
import pandas as pd
df=pd.read_csv("employees.csv")
ages=df["age"]
salaries=df["salary"]
ages_as_array=np.array(ages)
salaries_as_array=np.array(salaries)
#Print both Ages and Salaries arrays
print(ages_as_array,salaries_as_array)

#Display datatype of age and salary
print(ages_as_array.dtype,salaries_as_array.dtype)

#Display Dimension of age and salary
print(ages_as_array.ndim,salaries_as_array.ndim)

#Display Shape of age and salary 
print(ages_as_array.shape,salaries_as_array.shape)

#Display size of age and salary
print(ages_as_array.size,salaries_as_array.size)

[56 46 32 25 38 56 36 40 28 28] [77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
int64 int64
1 1
(10,) (10,)
10 10


***Q2. Using the salaries array, find and print the highest and lowest salary values. Also, calculate and print the average salary and age using NumPy functions.***

In [246]:
import numpy as np
import pandas as pd
df=pd.read_csv("employees.csv")
salaries=df["salary"]
ages=df["age"]
array_of_salary=np.array(salaries)
array_of_age=np.array(ages)

#Display Highest and Lowest Salary
highest_salary=np.max(array_of_salary)
lowest_salary=np.min(array_of_salary)
print(highest_salary,lowest_salary)

#Display Average Salary and Age 
average_of_salary=np.mean(array_of_salary)
average_of_age=np.mean(array_of_age)
print(average_of_salary,average_of_age)

89735 30769
57446.9 38.5


***Q3. From the ages array, filter and print all ages greater than 30 using a boolean condition. Then count and print how many employees are older than 30.***

In [248]:
import numpy as np
import pandas as pd
df=pd.read_csv("employees.csv")
ages=df["age"]
array_of_age=np.array(ages)

#Filter and print
greater_than_30=array_of_age>30
filtered_ages=array_of_age[greater_than_30]
print(filtered_ages)

# Count how many employees are older than 30.
Count=np.sum(greater_than_30)
print(Count)

[56 46 32 38 56 36 40]
7


***Q4. Create a new NumPy array that increases every employee’s age by 5 years (without modifying the original array). Print the new updated ages array.***

In [250]:
import numpy as np
import pandas as pd
df=pd.read_csv("employees.csv")
ages=df["age"]
array_of_age=np.array(ages)
Increases_age=array_of_age+5

#Print the new updated ages
print(Increases_age)

[61 51 37 30 43 61 41 45 33 33]


***Q5. Using NumPy, calculate the total salary expense (sum of all salaries) and the difference between the maximum and minimum salary. Print both results.***

In [252]:
import numpy as np
import pandas as pd
df=pd.read_csv("employees.csv")
salaries=df["salary"]
array_of_salary=np.array(salaries)

#Calculate Total Salary
total_salary=np.sum(array_of_salary)
print(total_salary)

#Calculate the difference between the maximum and minimum salary
maximum_salary=np.max(array_of_salary)
minimum_salary=np.min(array_of_salary)
difference=maximum_salary-minimum_salary
print(difference)

574469
58966


**Q6. Load the employees.csv file into a Pandas DataFrame. Display the first 5 rows, and check basic info using info() and summary statistics using describe().**

In [164]:
import numpy as np
import pandas as pd
df=pd.read_csv("employees.csv")
#Display first 5 rows
print(df.head(5))
print("\n")

#check basic information
print(df.info())
print("\n")

#Statical Summary
print(df.describe())

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes
None


             id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000


**Q7. Display only the id, age, and salary columns. Then show the last 3 rows using tail().**

In [171]:
import numpy as np
import pandas as pd
df=pd.read_csv("employees.csv")
df1=df[["id","age","salary"]]
df1.tail(3)

id  age  salary
7   8   40   86101
8   9   28   32433
9  10   28   35311

**Q8. Filter the DataFrame to show only employees who work in the IT department. Print the result and show the total number of IT employees.**

In [240]:
import numpy as np
import pandas as pd
df=pd.read_csv("employees.csv")
employees=df[df["dept"]=="IT"]
print(employees)
Count=np.sum(df["dept"]=="IT")
print(Count)

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT
3


**Q9. Sort the DataFrame by salary in descending order and display the top 3 highest-paid employees along with their department and age.**

In [242]:
import numpy as np
import pandas as pd
df=pd.read_csv("employees.csv")
sorted_df=df.sort_values("salary",ascending=False)
print(sorted_df[["id","salary","dept","age"]].head(3))

   id  salary     dept  age
6   7   89735  Finance   36
7   8   86101       IT   40
0   1   77191       HR   56


**Q10. Replace all salary values greater than 80000 with 80000 using loc. Then calculate and print the new average salary of all employees after replacement.**

In [238]:
import numpy as np
import pandas as pd
df=pd.read_csv("employees.csv")
df.loc[df["salary"]>80000,"salary"]=80000
Salary=df["salary"]
print(np.mean(Salary))

55863.3
